# Generated by Django 4.1 on 2022-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('emailaddress', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=1000)),
                ('checkbox', models.CharField(max_length=1)),
            ],
        ),
    ]
